// src/components/react/Cloudimage.jsx
import Img, { CloudimageProvider } from 'react-cloudimage-responsive-plain';

const cloudimageConfig = {
  token: 'ajrctguoxo',
  lazyLoading: true
};

export default function MySidebar(props) {
  return (
    <CloudimageProvider config={cloudimageConfig}>
      <Img src={props.src} params="org_if_sml=0&force_format=webp,jpeg&func=crop&gravity=face"/>
    </CloudimageProvider>
  );
};

// src/components/vue/CloudImage.vue
<script setup>
import Img, { CloudImageProvider } from 'vue-cloudimage-responsive-plain';

const cloudimageConfig = {
	token: 'ajrctguoxo',
	lazyLoading: true,
};
</script>

<template>
	<CloudImageProvider v-bind:cloudImageConfig="cloudimageConfig">
		<Img v-bind:src=src params="org_if_sml=0&force_format=webp,jpeg&func=crop&gravity=face" />
	</CloudImageProvider>
</template>

<script>
export default {
 props: {
   src: String
 }
}
</script>
